server:
  port: 8001

spring:
  application:
    name: springcloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapperLocations: classpath:club/jiajiajia/springcloud/payment/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl