server:
  port: 9527

spring:
  application:
    name: springcloud-gateway
  cloud:
    zookeeper:
      connect-string: 192.168.159.128:2181
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://springcloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://springcloud-payment-service
          predicates:
            - Path=/payment/create   #断言,路径相匹配的进行路由