server:
  port: 8085

spring:
  application:
    name: springcloud-consumer-zookeeper-hystirx-8085
  cloud:
    zookeeper:
      connect-string: 192.168.159.128:2181

feign:
  hystrix:
    enabled: true #如果true,自身的容错就开启。开启方式与生产端不一样。
