server:
  port: 8001

spring:
  application:
    name: springcloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapperLocations: classpath:club/jiajiajia/springcloud/payment/dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  client:
    #表示是否将自已注册进Eurekaserver认为true 。
    register-with-eureka: true
    #是否从Eurekaserver抓取已有的注册信息，默认为true。单节点无所训，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版